// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf__cC3G9CzqSRK-HMeGaKzM-TD3Cg3uU',
    appId: '1:111193751758:web:c0dceb42e55b4ba09fd09f',
    messagingSenderId: '111193751758',
    projectId: 'i7y932',
    authDomain: 'i7y932.firebaseapp.com',
    storageBucket: 'i7y932.firebasestorage.app',
    measurementId: 'G-D0TQ048YN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQFmDQYC5_VBcAyrG-FdS-8Sdg8kXCG2A',
    appId: '1:111193751758:android:74c9d0a03a13c4a59fd09f',
    messagingSenderId: '111193751758',
    projectId: 'i7y932',
    storageBucket: 'i7y932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXb0oq7Y6W3zh7tgsfuAGFb4coB1WJsUE',
    appId: '1:111193751758:ios:d940316fa5e5e8e09fd09f',
    messagingSenderId: '111193751758',
    projectId: 'i7y932',
    storageBucket: 'i7y932.firebasestorage.app',
    iosBundleId: 'com.example.gaiosophyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXb0oq7Y6W3zh7tgsfuAGFb4coB1WJsUE',
    appId: '1:111193751758:ios:d940316fa5e5e8e09fd09f',
    messagingSenderId: '111193751758',
    projectId: 'i7y932',
    storageBucket: 'i7y932.firebasestorage.app',
    iosBundleId: 'com.example.gaiosophyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf__cC3G9CzqSRK-HMeGaKzM-TD3Cg3uU',
    appId: '1:111193751758:web:802fcdb04ff2b81f9fd09f',
    messagingSenderId: '111193751758',
    projectId: 'i7y932',
    authDomain: 'i7y932.firebaseapp.com',
    storageBucket: 'i7y932.firebasestorage.app',
    measurementId: 'G-LCTD3HKC5S',
  );
}
