name: Debug App Store Connect Authentication

on:
  workflow_dispatch: # Manual trigger only

jobs:
  debug-auth:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check secrets are present
      run: |
        echo "Checking required secrets..."
        if [ -z "${{ secrets.APPSTORE_ISSUER_ID }}" ]; then
          echo "❌ APPSTORE_ISSUER_ID is missing"
        else
          echo "✅ APPSTORE_ISSUER_ID is present (length: $(echo '${{ secrets.APPSTORE_ISSUER_ID }}' | wc -c))"
        fi
        
        if [ -z "${{ secrets.APPSTORE_KEY_ID }}" ]; then
          echo "❌ APPSTORE_KEY_ID is missing"
        else
          echo "✅ APPSTORE_KEY_ID is present: ${{ secrets.APPSTORE_KEY_ID }}"
        fi
        
        if [ -z "${{ secrets.APPSTORE_PRIVATE_KEY }}" ]; then
          echo "❌ APPSTORE_PRIVATE_KEY is missing"
        else
          echo "✅ APPSTORE_PRIVATE_KEY is present (length: $(echo '${{ secrets.APPSTORE_PRIVATE_KEY }}' | wc -c))"
          echo "Private key preview (first 50 chars): $(echo '${{ secrets.APPSTORE_PRIVATE_KEY }}' | head -c 50)..."
        fi
        
    - name: Create and validate API key file
      run: |
        echo "Creating API key file..."
        mkdir -p ~/.appstoreconnect/private_keys/
        echo '${{ secrets.APPSTORE_PRIVATE_KEY }}' > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
        chmod 600 ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
        
        echo "Validating API key file format..."
        if head -1 ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8 | grep -q "BEGIN PRIVATE KEY"; then
          echo "✅ Private key has correct BEGIN header"
        else
          echo "❌ Private key missing BEGIN PRIVATE KEY header"
        fi
        
        if tail -1 ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8 | grep -q "END PRIVATE KEY"; then
          echo "✅ Private key has correct END header"
        else
          echo "❌ Private key missing END PRIVATE KEY header"
        fi
        
        echo "File size: $(wc -c < ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8) bytes"
        echo "Line count: $(wc -l < ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8) lines"
        
    - name: Test App Store Connect API connection
      run: |
        echo "Testing App Store Connect API authentication..."
        echo "Using Key ID: ${{ secrets.APPSTORE_KEY_ID }}"
        echo "Using Issuer ID: ${{ secrets.APPSTORE_ISSUER_ID }}"
        
        # Try a simple API call to test authentication
        xcrun altool --list-apps \
          --apiKey ${{ secrets.APPSTORE_KEY_ID }} \
          --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }} \
          --output-format json || echo "❌ API authentication failed"
          
    - name: Clean up
      if: always()
      run: |
        rm -f ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
