name: Build iOS App (Simplified)

on:
  workflow_dispatch: # Manual trigger only
  push:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.32.0'

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      continue-on-error: true
      
    - name: Clean previous builds
      run: |
        flutter clean
        cd ios
        rm -rf build/
        rm -rf Pods/
        rm -f Podfile.lock
        
    - name: Install CocoaPods
      run: |
        cd ios
        pod install --repo-update
        
    - name: Build Flutter iOS (no code signing)
      run: |
        flutter build ios --release --no-codesign
        
    - name: Check build outputs
      run: |
        echo "Checking build artifacts..."
        ls -la ios/build/
        if [ -d "ios/build/Release-iphoneos" ]; then
          echo "✅ iOS build completed successfully"
          ls -la ios/build/Release-iphoneos/
        else
          echo "❌ iOS build folder not found"
          exit 1
        fi
        
    - name: Create Archive (manual)
      run: |
        cd ios
        xcodebuild clean archive \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath ../build/Runner.xcarchive \
          -destination "generic/platform=iOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-outputs
        path: |
          build/Runner.xcarchive
          ios/build/Release-iphoneos/
        retention-days: 30
        
    - name: Build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Flutter dependencies installed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ CocoaPods dependencies resolved" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ iOS app built successfully" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Archive created (unsigned)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
        echo "1. Download the build artifacts" >> $GITHUB_STEP_SUMMARY
        echo "2. Sign the app manually with Xcode" >> $GITHUB_STEP_SUMMARY
        echo "3. Upload to TestFlight via App Store Connect" >> $GITHUB_STEP_SUMMARY
